package com.wissenup.domain.timetable.controller;
import com.wissenup.domain.timetable.dto.*; import com.wissenup.domain.timetable.entity.*; import com.wissenup.domain.timetable.service.TimetableService; import com.wissenup.shared.dto.ApiResponse; import com.wissenup.shared.security.SecurityContextUtil;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequiredArgsConstructor @RequestMapping("/api/v1")
public class TimetableController {
 private final TimetableService service; private Long org(){return SecurityContextUtil.getCurrentOrganizationId();}private Long user(){return SecurityContextUtil.getCurrentUserId();}private Long role(){return SecurityContextUtil.getCurrentRoleId();}private void tenant(Long requested){SecurityContextUtil.requireOrganizationAccess(requested);}
 @GetMapping("/timetable-periods") public ApiResponse<List<TimetablePeriod>> periods(@RequestParam(required=false)Long organizationId,@RequestParam(defaultValue="false")boolean includeInactive){tenant(organizationId);return ApiResponse.success(service.periods(org(),includeInactive));}
 @PostMapping("/timetable-periods") public ApiResponse<TimetablePeriod> createPeriod(@Valid @RequestBody TimetablePeriodRequest r){return ApiResponse.success("Period created",service.savePeriod(null,org(),user(),role(),r));}
 @PutMapping("/timetable-periods/{id}") public ApiResponse<TimetablePeriod> updatePeriod(@PathVariable Long id,@Valid @RequestBody TimetablePeriodRequest r){return ApiResponse.success("Period updated",service.savePeriod(id,org(),user(),role(),r));}
 @DeleteMapping("/timetable-periods/{id}") public ApiResponse<Void> deletePeriod(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);service.archivePeriod(id,org(),user(),role());return ApiResponse.success("Period archived");}
 @GetMapping("/class-timetables") public ApiResponse<List<ClassTimetable>> headers(@RequestParam(required=false)Long organizationId,@RequestParam Long academicYearId){tenant(organizationId);return ApiResponse.success(service.headers(org(),academicYearId));}
 @PostMapping("/class-timetables") public ApiResponse<ClassTimetable> createHeader(@Valid @RequestBody ClassTimetableRequest r){return ApiResponse.success("Class timetable created",service.createHeader(org(),user(),role(),r));}
 @DeleteMapping("/class-timetables/{id}") public ApiResponse<Void> deleteHeader(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);service.archiveHeader(id,org(),user(),role());return ApiResponse.success("Class timetable archived");}
 @GetMapping("/class-timetable-details") public ApiResponse<List<TimetableDetail>> details(@RequestParam(required=false)Long organizationId,@RequestParam Long classTimetableId){tenant(organizationId);return ApiResponse.success(service.details(org(),classTimetableId));}
 @PostMapping("/class-timetable-details") public ApiResponse<TimetableDetail> createDetail(@Valid @RequestBody TimetableDetailRequest r){return ApiResponse.success("Assignment created",service.saveDetail(null,org(),user(),role(),r));}
 @PutMapping("/class-timetable-details/{id}") public ApiResponse<TimetableDetail> updateDetail(@PathVariable Long id,@Valid @RequestBody TimetableDetailRequest r){return ApiResponse.success("Assignment updated",service.saveDetail(id,org(),user(),role(),r));}
 @DeleteMapping("/class-timetable-details/{id}") public ApiResponse<Void> deleteDetail(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);service.archiveDetail(id,org(),user(),role());return ApiResponse.success("Assignment removed");}
 @GetMapping("/teacher-substitutions") public ApiResponse<List<TeacherSubstitution>> substitutions(@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success(service.substitutions(org()));}
 @PostMapping("/teacher-substitutions") public ApiResponse<TeacherSubstitution> createSubstitution(@Valid @RequestBody TeacherSubstitutionRequest r){return ApiResponse.success("Substitution created",service.saveSubstitution(null,org(),user(),role(),r));}
 @PutMapping("/teacher-substitutions/{id}") public ApiResponse<TeacherSubstitution> updateSubstitution(@PathVariable Long id,@Valid @RequestBody TeacherSubstitutionRequest r){return ApiResponse.success("Substitution updated",service.saveSubstitution(id,org(),user(),role(),r));}
 @DeleteMapping("/teacher-substitutions/{id}") public ApiResponse<Void> deleteSubstitution(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);service.archiveSubstitution(id,org(),user(),role());return ApiResponse.success("Substitution cancelled");}
}
