package com.wissenup.domain.examination.controller;

import com.wissenup.shared.exception.ApiResponse;
import com.wissenup.shared.exception.ResourceNotFoundException;
import com.wissenup.shared.security.SecurityContextUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.sql.*;
import java.time.*;
import java.util.*;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/v1")
public class ExaminationController {
    private final JdbcTemplate jdbc;

    private Long org() { return SecurityContextUtil.getCurrentOrganizationId(); }
    private Long user() { return SecurityContextUtil.getCurrentUserId(); }
    private void tenant(Long requested) { SecurityContextUtil.requireOrganizationAccess(requested); }
    private Long number(Map<String,Object> body, String key) { Object value=body.get(key); return value==null?null:Long.valueOf(value.toString()); }
    private BigDecimal decimal(Map<String,Object> body,String key) { Object value=body.get(key);return value==null||value.toString().isBlank()?null:new BigDecimal(value.toString()); }
    private String text(Map<String,Object> body,String key) { Object value=body.get(key);return value==null?null:value.toString(); }
    private Long insert(String sql, Object... params) {
        KeyHolder key=new GeneratedKeyHolder();
        jdbc.update(connection->{PreparedStatement statement=connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);for(int i=0;i<params.length;i++)statement.setObject(i+1,params[i]);return statement;},key);
        return Objects.requireNonNull(key.getKey()).longValue();
    }
    private Map<String,Object> one(String sql,Object... params) {
        List<Map<String,Object>> rows=jdbc.queryForList(sql,params);if(rows.isEmpty())throw new ResourceNotFoundException("Examination record not found");return rows.getFirst();
    }

    @GetMapping("/exam-types")
    public ApiResponse<List<Map<String,Object>>> types(@RequestParam(required=false) Long organizationId,@RequestParam(defaultValue="false") boolean includeInactive){tenant(organizationId);return ApiResponse.success(jdbc.queryForList("select exam_type_id as \"examTypeId\",exam_type_name as \"examTypeName\",description,status from exam_types where organization_id=? "+(includeInactive?"":"and status='ACTIVE' ")+"order by exam_type_name",org()));}
    @PostMapping("/exam-types")
    public ApiResponse<Map<String,Object>> createType(@RequestBody Map<String,Object>b){Long id=insert("insert into exam_types(organization_id,exam_type_name,description,created_by) values(?,?,?,?)",org(),text(b,"examTypeName"),text(b,"description"),user());return ApiResponse.success("Exam type created",one("select exam_type_id as \"examTypeId\",exam_type_name as \"examTypeName\",description,status from exam_types where organization_id=? and exam_type_id=?",org(),id));}
    @PutMapping("/exam-types/{id}")
    public ApiResponse<Map<String,Object>> updateType(@PathVariable Long id,@RequestBody Map<String,Object>b){jdbc.update("update exam_types set exam_type_name=?,description=?,updated_at=current_timestamp,updated_by=? where exam_type_id=? and organization_id=?",text(b,"examTypeName"),text(b,"description"),user(),id,org());return ApiResponse.success("Exam type updated",one("select exam_type_id as \"examTypeId\",exam_type_name as \"examTypeName\",description,status from exam_types where organization_id=? and exam_type_id=?",org(),id));}
    @DeleteMapping("/exam-types/{id}") public ApiResponse<Void> archiveType(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);jdbc.update("update exam_types set status='INACTIVE',updated_at=current_timestamp,updated_by=? where exam_type_id=? and organization_id=?",user(),id,org());return ApiResponse.success("Exam type archived");}
    @PutMapping("/exam-types/{id}/restore") public ApiResponse<Void> restoreType(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);jdbc.update("update exam_types set status='ACTIVE',updated_at=current_timestamp,updated_by=? where exam_type_id=? and organization_id=?",user(),id,org());return ApiResponse.success("Exam type restored");}

    private static final String EXAM_SELECT="select exam_id as \"examId\",academic_year_id as \"academicYearId\",exam_type_id as \"examTypeId\",exam_name as \"examName\",start_date as \"startDate\",end_date as \"endDate\",status,remarks from exams where organization_id=? ";
    @GetMapping("/exams") public ApiResponse<List<Map<String,Object>>> exams(@RequestParam(required=false)Long organizationId,@RequestParam(required=false)Long academicYearId){tenant(organizationId);return ApiResponse.success(jdbc.queryForList(EXAM_SELECT+(academicYearId==null?"":"and academic_year_id=? ")+"order by start_date desc",academicYearId==null?new Object[]{org()}:new Object[]{org(),academicYearId}));}
    @GetMapping("/exams/{id}") public ApiResponse<Map<String,Object>> exam(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success(one(EXAM_SELECT+"and exam_id=?",org(),id));}
    @PostMapping("/exams") public ApiResponse<Map<String,Object>> createExam(@RequestBody Map<String,Object>b){validateDates(b);Long id=insert("insert into exams(organization_id,academic_year_id,exam_type_id,exam_name,start_date,end_date,status,remarks,created_by) values(?,?,?,?,?,?,?,?,?)",org(),number(b,"academicYearId"),number(b,"examTypeId"),text(b,"examName"),LocalDate.parse(text(b,"startDate")),LocalDate.parse(text(b,"endDate")),Optional.ofNullable(text(b,"status")).orElse("DRAFT"),text(b,"remarks"),user());return ApiResponse.success("Exam created",one(EXAM_SELECT+"and exam_id=?",org(),id));}
    @PutMapping("/exams/{id}") public ApiResponse<Map<String,Object>> updateExam(@PathVariable Long id,@RequestBody Map<String,Object>b){validateDates(b);jdbc.update("update exams set academic_year_id=?,exam_type_id=?,exam_name=?,start_date=?,end_date=?,status=?,remarks=?,updated_at=current_timestamp,updated_by=? where exam_id=? and organization_id=?",number(b,"academicYearId"),number(b,"examTypeId"),text(b,"examName"),LocalDate.parse(text(b,"startDate")),LocalDate.parse(text(b,"endDate")),text(b,"status"),text(b,"remarks"),user(),id,org());return ApiResponse.success("Exam updated",one(EXAM_SELECT+"and exam_id=?",org(),id));}
    @PutMapping("/exams/{id}/status") public ApiResponse<Void> examStatus(@PathVariable Long id,@RequestParam(required=false)Long organizationId,@RequestParam String status){tenant(organizationId);jdbc.update("update exams set status=?,updated_at=current_timestamp,updated_by=? where exam_id=? and organization_id=?",status,user(),id,org());return ApiResponse.success("Exam status updated");}
    private void validateDates(Map<String,Object>b){LocalDate start=LocalDate.parse(text(b,"startDate")),end=LocalDate.parse(text(b,"endDate"));if(end.isBefore(start))throw new IllegalArgumentException("Exam end date cannot be before its start date");}

    private static final String TARGET_SELECT="select exam_target_id as \"examTargetId\",exam_id as \"examId\",class_id as \"classId\",section_id as \"sectionId\",status from exam_targets where organization_id=? ";
    @GetMapping("/exam-targets") public ApiResponse<List<Map<String,Object>>> targets(@RequestParam(required=false)Long organizationId,@RequestParam Long examId){tenant(organizationId);return ApiResponse.success(jdbc.queryForList(TARGET_SELECT+"and exam_id=? order by class_id,section_id",org(),examId));}
    @PostMapping("/exam-targets") public ApiResponse<Map<String,Object>> createTarget(@RequestBody Map<String,Object>b){Long id=insert("insert into exam_targets(organization_id,exam_id,class_id,section_id,created_by) values(?,?,?,?,?)",org(),number(b,"examId"),number(b,"classId"),number(b,"sectionId"),user());return ApiResponse.success("Exam target created",one(TARGET_SELECT+"and exam_target_id=?",org(),id));}
    @DeleteMapping("/exam-targets/{id}") public ApiResponse<Void> archiveTarget(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);jdbc.update("update exam_targets set status='INACTIVE',updated_at=current_timestamp,updated_by=? where exam_target_id=? and organization_id=?",user(),id,org());return ApiResponse.success("Exam target archived");}
    @PutMapping("/exam-targets/{id}/restore") public ApiResponse<Void> restoreTarget(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);jdbc.update("update exam_targets set status='ACTIVE',updated_at=current_timestamp,updated_by=? where exam_target_id=? and organization_id=?",user(),id,org());return ApiResponse.success("Exam target restored");}

    private static final String PAPER_SELECT="select exam_timetable_id as \"examTimetableId\",exam_target_id as \"examTargetId\",subject_id as \"subjectId\",exam_date as \"examDate\",start_time as \"startTime\",end_time as \"endTime\",max_marks as \"maxMarks\",pass_marks as \"passMarks\",room_number as \"roomNumber\",status from exam_timetables where organization_id=? ";
    @GetMapping("/exam-timetables") public ApiResponse<List<Map<String,Object>>> papers(@RequestParam(required=false)Long organizationId,@RequestParam Long examTargetId){tenant(organizationId);return ApiResponse.success(jdbc.queryForList(PAPER_SELECT+"and exam_target_id=? order by exam_date,start_time",org(),examTargetId));}
    @PostMapping("/exam-timetables") public ApiResponse<Map<String,Object>> createPaper(@RequestBody Map<String,Object>b){validatePaper(b);Long id=insert("insert into exam_timetables(organization_id,exam_target_id,subject_id,exam_date,start_time,end_time,max_marks,pass_marks,room_number,created_by) values(?,?,?,?,?,?,?,?,?,?)",org(),number(b,"examTargetId"),number(b,"subjectId"),LocalDate.parse(text(b,"examDate")),LocalTime.parse(text(b,"startTime")),LocalTime.parse(text(b,"endTime")),decimal(b,"maxMarks"),decimal(b,"passMarks"),text(b,"roomNumber"),user());return ApiResponse.success("Exam paper scheduled",one(PAPER_SELECT+"and exam_timetable_id=?",org(),id));}
    @PutMapping("/exam-timetables/{id}") public ApiResponse<Map<String,Object>> updatePaper(@PathVariable Long id,@RequestBody Map<String,Object>b){validatePaper(b);jdbc.update("update exam_timetables set subject_id=?,exam_date=?,start_time=?,end_time=?,max_marks=?,pass_marks=?,room_number=?,updated_at=current_timestamp,updated_by=? where exam_timetable_id=? and organization_id=?",number(b,"subjectId"),LocalDate.parse(text(b,"examDate")),LocalTime.parse(text(b,"startTime")),LocalTime.parse(text(b,"endTime")),decimal(b,"maxMarks"),decimal(b,"passMarks"),text(b,"roomNumber"),user(),id,org());return ApiResponse.success("Exam paper updated",one(PAPER_SELECT+"and exam_timetable_id=?",org(),id));}
    @DeleteMapping("/exam-timetables/{id}") public ApiResponse<Void> cancelPaper(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);jdbc.update("update exam_timetables set status='CANCELLED',updated_at=current_timestamp,updated_by=? where exam_timetable_id=? and organization_id=?",user(),id,org());return ApiResponse.success("Exam paper cancelled");}
    private void validatePaper(Map<String,Object>b){BigDecimal max=decimal(b,"maxMarks"),pass=decimal(b,"passMarks");if(max==null||pass==null||max.signum()<=0||pass.signum()<0||pass.compareTo(max)>0)throw new IllegalArgumentException("Pass marks must be between zero and maximum marks");if(!LocalTime.parse(text(b,"endTime")).isAfter(LocalTime.parse(text(b,"startTime"))))throw new IllegalArgumentException("End time must be after start time");}

    @GetMapping("/student-marks/timetable/{id}") public ApiResponse<List<Map<String,Object>>> markRows(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);String sql="select s.student_id as \"studentId\",s.admission_no as \"admissionNo\",concat(s.first_name,' ',coalesce(s.last_name,'')) as \"studentName\",se.roll_no as \"rollNo\",sm.obtained_marks as \"obtainedMarks\",coalesce(sm.attendance_status,'PRESENT') as \"attendanceStatus\",sm.remarks from exam_timetables et join exam_targets t on t.exam_target_id=et.exam_target_id join exams e on e.exam_id=t.exam_id join student_enrollments se on se.organization_id=et.organization_id and se.academic_year_id=e.academic_year_id and se.class_id=t.class_id and se.section_id=t.section_id and se.status='ACTIVE' join students s on s.student_id=se.student_id left join student_marks sm on sm.exam_timetable_id=et.exam_timetable_id and sm.student_id=s.student_id where et.organization_id=? and et.exam_timetable_id=? order by coalesce(se.roll_no,''),s.first_name";return ApiResponse.success(jdbc.queryForList(sql,org(),id));}
    @PostMapping("/student-marks/bulk") public ApiResponse<Void> saveMarks(@RequestBody Map<String,Object>b){Long paperId=number(b,"examTimetableId"),enteredBy=Optional.ofNullable(number(b,"enteredBy")).orElse(user());BigDecimal max=jdbc.queryForObject("select max_marks from exam_timetables where organization_id=? and exam_timetable_id=?",BigDecimal.class,org(),paperId);for(Map<String,Object> row:(List<Map<String,Object>>)b.getOrDefault("marks",List.of())){Long student=number(row,"studentId");BigDecimal obtained=decimal(row,"obtainedMarks");String attendance=Optional.ofNullable(text(row,"attendanceStatus")).orElse("PRESENT");if(!"PRESENT".equals(attendance))obtained=null;if(obtained!=null&&obtained.compareTo(max)>0)throw new IllegalArgumentException("Obtained marks cannot exceed maximum marks");List<Long> ids=jdbc.query("select student_mark_id from student_marks where organization_id=? and exam_timetable_id=? and student_id=?",(rs,n)->rs.getLong(1),org(),paperId,student);if(ids.isEmpty())jdbc.update("insert into student_marks(organization_id,exam_timetable_id,student_id,obtained_marks,attendance_status,remarks,entered_by) values(?,?,?,?,?,?,?)",org(),paperId,student,obtained,attendance,text(row,"remarks"),enteredBy);else jdbc.update("update student_marks set obtained_marks=?,attendance_status=?,remarks=?,entered_by=?,updated_at=current_timestamp where student_mark_id=? and organization_id=?",obtained,attendance,text(row,"remarks"),enteredBy,ids.getFirst(),org());}return ApiResponse.success("Marks saved");}

    @GetMapping("/student-marks/timetable/{id}/submission") public ApiResponse<Map<String,Object>> submission(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);List<Map<String,Object>>rows=jdbc.queryForList("select mark_submission_id as \"markSubmissionId\",exam_timetable_id as \"examTimetableId\",status,submitted_by as \"submittedBy\",submitted_at as \"submittedAt\",reason from mark_submissions where organization_id=? and exam_timetable_id=?",org(),id);return ApiResponse.success(rows.isEmpty()?Map.of("examTimetableId",id,"status","DRAFT"):rows.getFirst());}
    @PostMapping("/student-marks/timetable/{id}/submit") public ApiResponse<Void> submit(@PathVariable Long id,@RequestParam(required=false)Long organizationId,@RequestParam Long submittedBy){tenant(organizationId);List<Long>ids=jdbc.query("select mark_submission_id from mark_submissions where organization_id=? and exam_timetable_id=?",(rs,n)->rs.getLong(1),org(),id);if(ids.isEmpty())jdbc.update("insert into mark_submissions(organization_id,exam_timetable_id,status,submitted_by,submitted_at) values(?,?,'SUBMITTED',?,current_timestamp)",org(),id,submittedBy);else jdbc.update("update mark_submissions set status='SUBMITTED',submitted_by=?,submitted_at=current_timestamp,reason=null where mark_submission_id=? and organization_id=?",submittedBy,ids.getFirst(),org());return ApiResponse.success("Marks submitted");}
    @GetMapping("/student-marks/submissions/pending") public ApiResponse<List<Map<String,Object>>> pending(@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success(jdbc.queryForList("select ms.mark_submission_id as \"markSubmissionId\",ms.exam_timetable_id as \"examTimetableId\",ms.status,ms.submitted_by as \"submittedBy\",ms.submitted_at as \"submittedAt\",e.exam_name as \"examName\",et.subject_id as \"subjectId\",t.class_id as \"classId\",t.section_id as \"sectionId\" from mark_submissions ms join exam_timetables et on et.exam_timetable_id=ms.exam_timetable_id join exam_targets t on t.exam_target_id=et.exam_target_id join exams e on e.exam_id=t.exam_id where ms.organization_id=? and ms.status='SUBMITTED' order by ms.submitted_at",org()));}
    @PutMapping("/student-marks/timetable/{id}/approve") public ApiResponse<Void> approve(@PathVariable Long id,@RequestBody Map<String,Object>b){action(id,"APPROVED",b);return ApiResponse.success("Marks approved");}
    @PutMapping("/student-marks/timetable/{id}/reject") public ApiResponse<Void> reject(@PathVariable Long id,@RequestBody Map<String,Object>b){if(text(b,"reason")==null||text(b,"reason").isBlank())throw new IllegalArgumentException("A rejection reason is required");action(id,"REJECTED",b);return ApiResponse.success("Marks returned for correction");}
    private void action(Long id,String status,Map<String,Object>b){jdbc.update("update mark_submissions set status=?,actioned_by_user_id=?,actioned_by_staff_id=?,actioned_by_role=?,actioned_at=current_timestamp,reason=? where organization_id=? and exam_timetable_id=?",status,number(b,"actionedByUserId"),number(b,"actionedByStaffId"),text(b,"actionedByRole"),text(b,"reason"),org(),id);}

    @GetMapping("/exam-results/target/{targetId}") public ApiResponse<List<Map<String,Object>>> results(@PathVariable Long targetId,@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success(calculate(targetId,null));}
    @GetMapping("/exam-results/target/{targetId}/student/{studentId}") public ApiResponse<Map<String,Object>> report(@PathVariable Long targetId,@PathVariable Long studentId,@RequestParam(required=false)Long organizationId){tenant(organizationId);Map<String,Object> selected=calculate(targetId,null).stream().filter(row->Objects.equals(((Number)row.get("studentId")).longValue(),studentId)).findFirst().orElseThrow(()->new ResourceNotFoundException("Report card is unavailable"));Map<String,Object> report=new LinkedHashMap<>(selected);String sql="select et.exam_timetable_id as \"examTimetableId\",sub.subject_name as \"subjectName\",et.max_marks as \"maxMarks\",et.pass_marks as \"passMarks\",sm.obtained_marks as \"obtainedMarks\",coalesce(sm.attendance_status,'NOT_ENTERED') as \"attendanceStatus\" from exam_timetables et join subjects sub on sub.subject_id=et.subject_id left join student_marks sm on sm.exam_timetable_id=et.exam_timetable_id and sm.student_id=? where et.organization_id=? and et.exam_target_id=? and et.status<>'CANCELLED' order by et.exam_date,sub.subject_name";List<Map<String,Object>>subjects=jdbc.queryForList(sql,studentId,org(),targetId);for(Map<String,Object>s:subjects){BigDecimal obtained=(BigDecimal)s.get("obtainedMarks"),pass=(BigDecimal)s.get("passMarks"),max=(BigDecimal)s.get("maxMarks");boolean absent=obtained==null;String result=absent?"ABSENT":obtained.compareTo(pass)>=0?"PASS":"FAIL";s.put("result",result);s.put("grade",absent?"-":grade(obtained.multiply(BigDecimal.valueOf(100)).divide(max,2,java.math.RoundingMode.HALF_UP).doubleValue()));}report.put("subjects",subjects);return ApiResponse.success(report);}
    private List<Map<String,Object>> calculate(Long targetId,Long onlyStudent){String sql="select s.student_id as \"studentId\",s.admission_no as \"admissionNo\",concat(s.first_name,' ',coalesce(s.last_name,'')) as \"studentName\",se.roll_no as \"rollNo\",c.class_name as \"className\",sec.section_name as \"sectionName\",e.exam_name as \"examName\",coalesce(sum(et.max_marks),0) as \"totalMarks\",coalesce(sum(case when sm.attendance_status='PRESENT' then sm.obtained_marks else 0 end),0) as \"marksObtained\",sum(case when sm.student_mark_id is null or sm.attendance_status<>'PRESENT' or sm.obtained_marks<et.pass_marks then 1 else 0 end) as failures from exam_targets t join exams e on e.exam_id=t.exam_id join classes c on c.class_id=t.class_id join sections sec on sec.section_id=t.section_id join student_enrollments se on se.organization_id=t.organization_id and se.academic_year_id=e.academic_year_id and se.class_id=t.class_id and se.section_id=t.section_id and se.status='ACTIVE' join students s on s.student_id=se.student_id join exam_timetables et on et.exam_target_id=t.exam_target_id and et.status<>'CANCELLED' left join student_marks sm on sm.exam_timetable_id=et.exam_timetable_id and sm.student_id=s.student_id where t.organization_id=? and t.exam_target_id=? "+(onlyStudent==null?"":"and s.student_id=? ")+"group by s.student_id,s.admission_no,s.first_name,s.last_name,se.roll_no,c.class_name,sec.section_name,e.exam_name order by \"marksObtained\" desc,s.first_name";List<Map<String,Object>>rows=jdbc.queryForList(sql,onlyStudent==null?new Object[]{org(),targetId}:new Object[]{org(),targetId,onlyStudent});int rank=0;BigDecimal previous=null;for(int i=0;i<rows.size();i++){Map<String,Object>r=rows.get(i);BigDecimal total=(BigDecimal)r.get("totalMarks"),obtained=(BigDecimal)r.get("marksObtained");double pct=total.signum()==0?0:obtained.multiply(BigDecimal.valueOf(100)).divide(total,2,java.math.RoundingMode.HALF_UP).doubleValue();if(previous==null||obtained.compareTo(previous)!=0)rank=i+1;previous=obtained;r.put("percentage",pct);r.put("grade",grade(pct));r.put("resultStatus",((Number)r.remove("failures")).longValue()==0?"PASS":"FAIL");r.put("rank",rank);}return rows;}
    private String grade(double p){return p>=90?"A+":p>=80?"A":p>=70?"B+":p>=60?"B":p>=50?"C":p>=40?"D":"F";}
}
