package com.wissenup.domain.timetable.service;
import com.wissenup.domain.timetable.dto.*; import com.wissenup.domain.timetable.entity.*; import com.wissenup.domain.timetable.repository.*;
import com.wissenup.domain.academic.repository.*; import com.wissenup.domain.identity.repository.RoleRepository; import com.wissenup.domain.staff.repository.*;
import com.wissenup.domain.staff.entity.StaffSubjectAssignment;
import com.wissenup.shared.exception.*; import lombok.RequiredArgsConstructor; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor @Transactional
public class TimetableService {
 private final TimetablePeriodRepository periods; private final ClassTimetableRepository headers; private final TimetableDetailRepository details; private final TeacherSubstitutionRepository substitutions;
 private final AcademicYearRepository years; private final ClassRepository classes; private final SectionRepository sections; private final ClassSubjectRepository classSubjects;
 private final StaffRepository staff; private final StaffSubjectAssignmentRepository staffSubjects; private final RoleRepository roles;

 @Transactional(readOnly=true) public List<TimetablePeriod> periods(Long org,boolean includeInactive){return periods.findAllByOrganizationIdOrderByDisplayOrder(org).stream().filter(p->includeInactive||"ACTIVE".equalsIgnoreCase(p.getStatus())).toList();}
 public TimetablePeriod savePeriod(Long id,Long org,Long user,Long role,TimetablePeriodRequest r){requireAdmin(role);if(!r.getEndTime().isAfter(r.getStartTime()))throw new ValidationException("End time must be after start time");
  TimetablePeriod p=id==null?TimetablePeriod.builder().organizationId(org).createdBy(user).status("ACTIVE").build():period(id,org);p.setPeriodName(r.getPeriodName().trim());p.setStartTime(r.getStartTime());p.setEndTime(r.getEndTime());p.setIsBreak(r.getIsBreak());p.setDisplayOrder(r.getDisplayOrder());p.setUpdatedBy(user);return periods.save(p);}
 public void archivePeriod(Long id,Long org,Long user,Long role){requireAdmin(role);TimetablePeriod p=period(id,org);if(!details.findAllByOrganizationIdAndPeriodIdAndStatusIgnoreCase(org,id,"ACTIVE").isEmpty())throw new ConflictException("This period is used in a timetable. Remove its assignments first");p.setStatus("INACTIVE");p.setUpdatedBy(user);periods.save(p);}

 @Transactional(readOnly=true) public List<ClassTimetable> headers(Long org,Long year){return headers.findAllByOrganizationIdAndAcademicYearIdOrderByClassIdAscSectionIdAsc(org,year);}
 public ClassTimetable createHeader(Long org,Long user,Long role,ClassTimetableRequest r){requireAdmin(role);validatePlacement(org,r);var existing=headers.findByOrganizationIdAndAcademicYearIdAndClassIdAndSectionId(org,r.getAcademicYearId(),r.getClassId(),r.getSectionId());if(existing.isPresent()){ClassTimetable h=existing.get();if("ACTIVE".equalsIgnoreCase(h.getStatus()))return h;h.setStatus("ACTIVE");h.setUpdatedBy(user);return headers.save(h);}return headers.save(ClassTimetable.builder().organizationId(org).academicYearId(r.getAcademicYearId()).classId(r.getClassId()).sectionId(r.getSectionId()).status("ACTIVE").createdBy(user).build());}
 public void archiveHeader(Long id,Long org,Long user,Long role){requireAdmin(role);ClassTimetable h=header(id,org);h.setStatus("INACTIVE");h.setUpdatedBy(user);headers.save(h);details.findAllByOrganizationIdAndClassTimetableIdAndStatusIgnoreCase(org,id,"ACTIVE").forEach(d->{d.setStatus("INACTIVE");d.setUpdatedBy(user);details.save(d);});}

 @Transactional(readOnly=true) public List<TimetableDetail> details(Long org,Long headerId){header(headerId,org);return details.findAllByOrganizationIdAndClassTimetableIdOrderByDayOfWeekAscPeriodIdAsc(org,headerId);}
 public TimetableDetail saveDetail(Long id,Long org,Long user,Long role,TimetableDetailRequest r){requireAdmin(role);ClassTimetable h=header(r.getClassTimetableId(),org);if(!"ACTIVE".equalsIgnoreCase(h.getStatus()))throw new ValidationException("Class timetable is inactive");TimetablePeriod p=period(r.getPeriodId(),org);if(!"ACTIVE".equalsIgnoreCase(p.getStatus())||Boolean.TRUE.equals(p.getIsBreak()))throw new ValidationException("A teaching assignment cannot use an inactive or break period");String day=day(r.getDayOfWeek());long excluded=id==null?-1L:id;
  if(details.existsByClassTimetableIdAndDayOfWeekAndPeriodIdAndStatusIgnoreCaseAndTimetableDetailIdNot(h.getClassTimetableId(),day,p.getPeriodId(),"ACTIVE",excluded))throw new ConflictException("This class already has an assignment for the selected day and period");
  if(details.existsByOrganizationIdAndStaffIdAndDayOfWeekAndPeriodIdAndStatusIgnoreCaseAndTimetableDetailIdNot(org,r.getStaffId(),day,p.getPeriodId(),"ACTIVE",excluded))throw new ConflictException("The selected teacher is already assigned during this period");
  var mapped=classSubjects.findByOrganizationIdAndClassIdAndSubjectId(org,h.getClassId(),r.getSubjectId()).filter(v->"ACTIVE".equalsIgnoreCase(v.getStatus().name())).orElseThrow(()->new ValidationException("The selected subject is not mapped to this class"));
  var selectedStaff=staff.findByStaffIdAndOrganizationId(r.getStaffId(),org).filter(v->"ACTIVE".equalsIgnoreCase(v.getStatus())).orElseThrow(()->ResourceNotFoundException.notFound("Active staff",r.getStaffId()));
  if(!"TEACHER".equalsIgnoreCase(selectedStaff.getRoleName()))throw new ValidationException("Only teaching staff can be assigned to a timetable slot");
  if(!staffSubjects.existsByOrganizationIdAndStaffIdAndAcademicYearIdAndClassIdAndSectionIdAndSubjectIdAndStatusIgnoreCase(org,r.getStaffId(),h.getAcademicYearId(),h.getClassId(),h.getSectionId(),mapped.getSubjectId(),"ACTIVE")){
   StaffSubjectAssignment assignment=staffSubjects.findByOrganizationIdAndStaffIdAndAcademicYearIdAndClassIdAndSectionIdAndSubjectId(org,r.getStaffId(),h.getAcademicYearId(),h.getClassId(),h.getSectionId(),mapped.getSubjectId()).orElseGet(()->StaffSubjectAssignment.builder().organizationId(org).staffId(r.getStaffId()).academicYearId(h.getAcademicYearId()).classId(h.getClassId()).sectionId(h.getSectionId()).subjectId(mapped.getSubjectId()).createdBy(user).build());assignment.setStatus("ACTIVE");staffSubjects.save(assignment);
  }
  TimetableDetail d=id==null?details.findByClassTimetableIdAndDayOfWeekAndPeriodId(h.getClassTimetableId(),day,p.getPeriodId()).orElseGet(()->TimetableDetail.builder().organizationId(org).createdBy(user).status("ACTIVE").build()):detail(id,org);d.setClassTimetableId(h.getClassTimetableId());d.setDayOfWeek(day);d.setPeriodId(p.getPeriodId());d.setSubjectId(r.getSubjectId());d.setStaffId(r.getStaffId());d.setRoomNumber(blank(r.getRoomNumber()));d.setStatus("ACTIVE");d.setUpdatedBy(user);return details.save(d);}
 public void archiveDetail(Long id,Long org,Long user,Long role){requireAdmin(role);TimetableDetail d=detail(id,org);d.setStatus("INACTIVE");d.setUpdatedBy(user);details.save(d);}

 @Transactional(readOnly=true) public List<TeacherSubstitution> substitutions(Long org){return substitutions.findAllByOrganizationIdOrderBySubstitutionDateDesc(org);}
 public TeacherSubstitution saveSubstitution(Long id,Long org,Long user,Long role,TeacherSubstitutionRequest r){requireAdmin(role);TimetableDetail detail=detail(r.getTimetableDetailId(),org);if(!"ACTIVE".equalsIgnoreCase(detail.getStatus()))throw new ValidationException("Timetable assignment is inactive");String scheduled=detail.getDayOfWeek();if(!r.getSubstitutionDate().getDayOfWeek().name().equals(scheduled))throw new ValidationException("Substitution date must fall on "+scheduled);
  staff.findByStaffIdAndOrganizationId(r.getSubstituteStaffId(),org).filter(v->"ACTIVE".equalsIgnoreCase(v.getStatus())).orElseThrow(()->ResourceNotFoundException.notFound("Active substitute staff",r.getSubstituteStaffId()));if(Objects.equals(detail.getStaffId(),r.getSubstituteStaffId()))throw new ValidationException("Substitute teacher must be different from the regular teacher");long excluded=id==null?-1L:id;if(substitutions.existsByTimetableDetailIdAndSubstitutionDateAndStatusIgnoreCaseAndSubstitutionIdNot(r.getTimetableDetailId(),r.getSubstitutionDate(),"ACTIVE",excluded))throw new ConflictException("A substitution already exists for this assignment and date");
  TeacherSubstitution s=id==null?substitutions.findByTimetableDetailIdAndSubstitutionDate(r.getTimetableDetailId(),r.getSubstitutionDate()).orElseGet(()->TeacherSubstitution.builder().organizationId(org).createdBy(user).status("ACTIVE").build()):substitution(id,org);s.setTimetableDetailId(r.getTimetableDetailId());s.setSubstitutionDate(r.getSubstitutionDate());s.setSubstituteStaffId(r.getSubstituteStaffId());s.setReason(blank(r.getReason()));s.setStatus("ACTIVE");s.setUpdatedBy(user);return substitutions.save(s);}
 public void archiveSubstitution(Long id,Long org,Long user,Long role){requireAdmin(role);TeacherSubstitution s=substitution(id,org);s.setStatus("CANCELLED");s.setUpdatedBy(user);substitutions.save(s);}

 private void validatePlacement(Long org,ClassTimetableRequest r){var y=years.findById(r.getAcademicYearId()).filter(v->org.equals(v.getOrganizationId())).orElseThrow(()->ResourceNotFoundException.notFound("Academic year",r.getAcademicYearId()));var c=classes.findById(r.getClassId()).filter(v->org.equals(v.getOrganizationId())&&y.getAcademicYearId().equals(v.getAcademicYearId())).orElseThrow(()->ResourceNotFoundException.notFound("Class",r.getClassId()));sections.findById(r.getSectionId()).filter(v->org.equals(v.getOrganizationId())&&c.getClassId().equals(v.getClassId())).orElseThrow(()->ResourceNotFoundException.notFound("Section",r.getSectionId()));}
 private void requireAdmin(Long roleId){String code=roles.findById(roleId).map(v->v.getCode()).orElse("");if(!Set.of("SCHOOL_ADMIN","SUPER_ADMIN").contains(code))throw new AccessDeniedException("Only a school administrator can modify the timetable");}
 private TimetablePeriod period(Long id,Long org){return periods.findByPeriodIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Timetable period",id));} private ClassTimetable header(Long id,Long org){return headers.findByClassTimetableIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Class timetable",id));} private TimetableDetail detail(Long id,Long org){return details.findByTimetableDetailIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Timetable detail",id));} private TeacherSubstitution substitution(Long id,Long org){return substitutions.findBySubstitutionIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Teacher substitution",id));}
 private String day(String d){try{return DayOfWeek.valueOf(d.trim().toUpperCase()).name();}catch(Exception e){throw new ValidationException("Invalid day of week");}} private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
}
