package com.wissenup.domain.communication.controller;
import com.wissenup.domain.communication.dto.*;import com.wissenup.domain.communication.entity.*;import com.wissenup.domain.communication.service.CommunicationService;import com.wissenup.shared.dto.ApiResponse;import com.wissenup.shared.security.SecurityContextUtil;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;import java.util.List;
@RestController @RequiredArgsConstructor @RequestMapping("/api/v1") public class CommunicationController {
 private final CommunicationService service;private Long org(){return SecurityContextUtil.getCurrentOrganizationId();}private Long user(){return SecurityContextUtil.getCurrentUserId();}private Long role(){return SecurityContextUtil.getCurrentRoleId();}private void tenant(Long id){SecurityContextUtil.requireOrganizationAccess(id);}
 @GetMapping("/calendar") public ApiResponse<List<CalendarEvent>> calendar(@RequestParam(required=false)Long organizationId,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(defaultValue="false")boolean includeInactive){tenant(organizationId);return ApiResponse.success(service.calendar(org(),role(),startDate,endDate,includeInactive));}
 @PostMapping("/calendar") public ApiResponse<CalendarEvent> createEvent(@Valid @RequestBody CalendarEventRequest r){return ApiResponse.success("Event created",service.saveCalendar(null,org(),user(),role(),r));}@PutMapping("/calendar/{id}") public ApiResponse<CalendarEvent> updateEvent(@PathVariable Long id,@Valid @RequestBody CalendarEventRequest r){return ApiResponse.success("Event updated",service.saveCalendar(id,org(),user(),role(),r));}@DeleteMapping("/calendar/{id}") public ApiResponse<CalendarEvent> archiveEvent(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success("Event archived",service.calendarStatus(id,org(),user(),role(),"INACTIVE"));}@PutMapping("/calendar/{id}/restore") public ApiResponse<CalendarEvent> restoreEvent(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success("Event restored",service.calendarStatus(id,org(),user(),role(),"ACTIVE"));}
 @GetMapping("/notices") public ApiResponse<List<Notice>> notices(@RequestParam(required=false)Long organizationId,@RequestParam(defaultValue="false")boolean includeInactive,@RequestParam(required=false)String noticeType){tenant(organizationId);return ApiResponse.success(service.noticeList(org(),role(),includeInactive,noticeType));}@GetMapping("/notices/published") public ApiResponse<List<Notice>> published(@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success(service.published(org()));}
 @PostMapping("/notices") public ApiResponse<Notice> createNotice(@Valid @RequestBody NoticeRequest r){return ApiResponse.success("Notice created",service.saveNotice(null,org(),user(),role(),r));}@PutMapping("/notices/{id}") public ApiResponse<Notice> updateNotice(@PathVariable Long id,@Valid @RequestBody NoticeRequest r){return ApiResponse.success("Notice updated",service.saveNotice(id,org(),user(),role(),r));}@DeleteMapping("/notices/{id}") public ApiResponse<Notice> archiveNotice(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success("Notice archived",service.noticeStatus(id,org(),user(),role(),"INACTIVE"));}@PutMapping("/notices/{id}/restore") public ApiResponse<Notice> restoreNotice(@PathVariable Long id,@RequestParam(required=false)Long organizationId){tenant(organizationId);return ApiResponse.success("Notice restored",service.noticeStatus(id,org(),user(),role(),"ACTIVE"));}
}
