package com.wissenup.domain.communication.service;
import com.wissenup.domain.communication.dto.*; import com.wissenup.domain.communication.entity.*; import com.wissenup.domain.communication.repository.*; import com.wissenup.domain.identity.repository.RoleRepository; import com.wissenup.domain.staff.entity.Staff; import com.wissenup.domain.staff.repository.*; import com.wissenup.shared.exception.*;
import lombok.RequiredArgsConstructor; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class CommunicationService {
 private final CalendarEventRepository calendar;private final NoticeRepository notices;private final RoleRepository roles;private final StaffRepository staff;private final StaffClassAssignmentRepository classAssignments;
 @Transactional(readOnly=true) public List<CalendarEvent> calendar(Long org,Long roleId,LocalDate start,LocalDate end,boolean includeInactive){boolean admin=isAdmin(roleId);return calendar.findAllByOrganizationIdOrderByStartDateAsc(org).stream().filter(e->(includeInactive&&admin)||"ACTIVE".equalsIgnoreCase(e.getStatus())).filter(e->start==null||(e.getEndDate()==null?e.getStartDate():e.getEndDate()).compareTo(start)>=0).filter(e->end==null||e.getStartDate().compareTo(end)<=0).toList();}
 public CalendarEvent saveCalendar(Long id,Long org,Long user,Long role,CalendarEventRequest r){requireAdmin(role);if(r.getEndDate()!=null&&r.getEndDate().isBefore(r.getStartDate()))throw new ValidationException("End date cannot be before start date");CalendarEvent e=id==null?CalendarEvent.builder().organizationId(org).createdBy(user).build():event(id,org);e.setTitle(r.getTitle().trim());e.setDescription(blank(r.getDescription()));e.setEventType(r.getEventType().trim().toUpperCase());e.setStartDate(r.getStartDate());e.setEndDate(r.getEndDate());e.setIsHoliday(Boolean.TRUE.equals(r.getIsHoliday())||"HOLIDAY".equals(e.getEventType()));e.setColorCode(blank(r.getColorCode()));e.setStatus(normalStatus(r.getStatus()));e.setUpdatedBy(user);return calendar.save(e);}
 public CalendarEvent calendarStatus(Long id,Long org,Long user,Long role,String status){requireAdmin(role);CalendarEvent e=event(id,org);e.setStatus(status);e.setUpdatedBy(user);return calendar.save(e);}
 @Transactional(readOnly=true) public List<Notice> noticeList(Long org,Long roleId,boolean includeInactive,String type){boolean admin=isAdmin(roleId);return notices.findAllByOrganizationIdOrderByPublishDateDescCreatedAtDesc(org).stream().filter(n->(includeInactive&&admin)||!"INACTIVE".equalsIgnoreCase(n.getStatus())).filter(n->type==null||type.equalsIgnoreCase(n.getNoticeType())).toList();}
 @Transactional(readOnly=true) public List<Notice> published(Long org){LocalDate today=LocalDate.now();return notices.findAllByOrganizationIdOrderByPublishDateDescCreatedAtDesc(org).stream().filter(n->"ACTIVE".equalsIgnoreCase(n.getStatus())&&!n.getPublishDate().isAfter(today)&&(n.getExpiryDate()==null||!n.getExpiryDate().isBefore(today))).toList();}
 public Notice saveNotice(Long id,Long org,Long user,Long role,NoticeRequest r){if(id==null)requireNoticeCreator(org,user,role);else requireAdmin(role);if(r.getExpiryDate()!=null&&r.getExpiryDate().isBefore(r.getPublishDate()))throw new ValidationException("Expiry date cannot be before publish date");Notice n=id==null?Notice.builder().organizationId(org).createdBy(user).build():notice(id,org);n.setTitle(r.getTitle().trim());n.setDescription(r.getDescription().trim());n.setNoticeType(r.getNoticeType().trim().toUpperCase());n.setPublishDate(r.getPublishDate());n.setExpiryDate(r.getExpiryDate());n.setAttachmentUrl(blank(r.getAttachmentUrl()));n.setStatus(normalStatus(r.getStatus()));n.setUpdatedBy(user);return notices.save(n);}
 public Notice noticeStatus(Long id,Long org,Long user,Long role,String status){requireAdmin(role);Notice n=notice(id,org);n.setStatus(status);n.setUpdatedBy(user);return notices.save(n);}
 private void requireNoticeCreator(Long org,Long user,Long role){if(isAdmin(role))return;Long staffId=staff.findByUserIdAndOrganizationId(user,org).map(Staff::getStaffId).orElse(null);if(staffId==null||!classAssignments.existsByOrganizationIdAndStaffIdAndStatusIgnoreCase(org,staffId,"ACTIVE"))throw new AccessDeniedException("Only a school administrator or assigned class teacher can create notices");}
 private boolean isAdmin(Long role){String code=roles.findById(role).map(v->v.getCode()).orElse("");return Set.of("SCHOOL_ADMIN","ORG_ADMIN","SUPER_ADMIN").contains(code);}private void requireAdmin(Long role){if(!isAdmin(role))throw new AccessDeniedException("Only a school administrator can manage this resource");}
 private CalendarEvent event(Long id,Long org){return calendar.findByCalendarIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Calendar event",id));}private Notice notice(Long id,Long org){return notices.findByNoticeIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Notice",id));}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}private String normalStatus(String s){return s==null||s.isBlank()?"ACTIVE":s.trim().toUpperCase();}
}
