CREATE TABLE staff_class_assignments (
    staff_class_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    CONSTRAINT fk_staff_class_assignment_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id) ON DELETE CASCADE,
    CONSTRAINT uq_staff_class_assignment UNIQUE (organization_id, staff_id, academic_year_id, class_id, section_id)
);

CREATE TABLE staff_subject_assignments (
    staff_subject_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    CONSTRAINT fk_staff_subject_assignment_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id) ON DELETE CASCADE,
    CONSTRAINT uq_staff_subject_assignment UNIQUE (organization_id, staff_id, academic_year_id, class_id, section_id, subject_id)
);

CREATE INDEX idx_staff_class_assignment_staff ON staff_class_assignments (organization_id, staff_id);
CREATE INDEX idx_staff_subject_assignment_staff ON staff_subject_assignments (organization_id, staff_id);
