CREATE TABLE attendance_sessions (
    attendance_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    session_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    marked_by_user_id BIGINT NOT NULL,
    marked_by_staff_id BIGINT,
    marked_by_role VARCHAR(100) NOT NULL,
    remarks VARCHAR(500),
    submitted_at TIMESTAMP,
    actioned_by_user_id BIGINT,
    actioned_by_staff_id BIGINT,
    actioned_by_role VARCHAR(100),
    actioned_at TIMESTAMP,
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_attendance_session UNIQUE
      (organization_id, academic_year_id, class_id, section_id, attendance_date, session_type),
    CONSTRAINT ck_attendance_session_status CHECK
      (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_att_session_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
    CONSTRAINT fk_att_session_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(academic_year_id),
    CONSTRAINT fk_att_session_class FOREIGN KEY (class_id) REFERENCES classes(class_id),
    CONSTRAINT fk_att_session_section FOREIGN KEY (section_id) REFERENCES sections(section_id),
    CONSTRAINT fk_att_session_user FOREIGN KEY (marked_by_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_att_session_staff FOREIGN KEY (marked_by_staff_id) REFERENCES staff(staff_id),
    CONSTRAINT fk_att_action_user FOREIGN KEY (actioned_by_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_att_action_staff FOREIGN KEY (actioned_by_staff_id) REFERENCES staff(staff_id)
);

CREATE INDEX idx_attendance_sessions_lookup ON attendance_sessions
  (organization_id, academic_year_id, class_id, section_id, attendance_date);
CREATE INDEX idx_attendance_sessions_approval ON attendance_sessions (organization_id, status);

CREATE TABLE student_attendance (
    student_attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    attendance_session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    attendance_status VARCHAR(20) NOT NULL,
    remarks VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    CONSTRAINT uq_student_attendance UNIQUE (attendance_session_id, student_id),
    CONSTRAINT ck_student_attendance_status CHECK
      (attendance_status IN ('PRESENT', 'ABSENT', 'LATE', 'LEAVE')),
    CONSTRAINT fk_student_attendance_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
    CONSTRAINT fk_student_attendance_session FOREIGN KEY (attendance_session_id)
      REFERENCES attendance_sessions(attendance_session_id) ON DELETE CASCADE,
    CONSTRAINT fk_student_attendance_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_student_attendance_user FOREIGN KEY (created_by) REFERENCES users(user_id)
);

CREATE INDEX idx_student_attendance_student ON student_attendance (organization_id, student_id);
