CREATE TABLE timetable_periods (
 period_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id BIGINT NOT NULL,
 period_name VARCHAR(100) NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL,
 is_break BOOLEAN NOT NULL DEFAULT FALSE, display_order INTEGER NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL,
 updated_at TIMESTAMP, updated_by BIGINT,
 CONSTRAINT ck_timetable_period_time CHECK (end_time > start_time),
 CONSTRAINT fk_timetable_period_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id)
);

CREATE TABLE class_timetables (
 class_timetable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id BIGINT NOT NULL,
 academic_year_id BIGINT NOT NULL, class_id BIGINT NOT NULL, section_id BIGINT NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL, updated_at TIMESTAMP, updated_by BIGINT,
 CONSTRAINT uq_class_timetable UNIQUE (organization_id, academic_year_id, class_id, section_id),
 CONSTRAINT fk_class_tt_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
 CONSTRAINT fk_class_tt_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(academic_year_id),
 CONSTRAINT fk_class_tt_class FOREIGN KEY (class_id) REFERENCES classes(class_id),
 CONSTRAINT fk_class_tt_section FOREIGN KEY (section_id) REFERENCES sections(section_id)
);

CREATE TABLE class_timetable_details (
 timetable_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id BIGINT NOT NULL,
 class_timetable_id BIGINT NOT NULL, day_of_week VARCHAR(15) NOT NULL, period_id BIGINT NOT NULL,
 subject_id BIGINT NOT NULL, staff_id BIGINT NOT NULL, room_number VARCHAR(100),
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL, updated_at TIMESTAMP, updated_by BIGINT,
 CONSTRAINT uq_class_tt_slot UNIQUE (class_timetable_id, day_of_week, period_id),
 CONSTRAINT ck_class_tt_day CHECK (day_of_week IN ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
 CONSTRAINT fk_tt_detail_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
 CONSTRAINT fk_tt_detail_header FOREIGN KEY (class_timetable_id) REFERENCES class_timetables(class_timetable_id),
 CONSTRAINT fk_tt_detail_period FOREIGN KEY (period_id) REFERENCES timetable_periods(period_id),
 CONSTRAINT fk_tt_detail_subject FOREIGN KEY (subject_id) REFERENCES subjects(subject_id),
 CONSTRAINT fk_tt_detail_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);
CREATE INDEX idx_tt_teacher_slot ON class_timetable_details (organization_id, staff_id, day_of_week, period_id, status);

CREATE TABLE teacher_substitutions (
 substitution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id BIGINT NOT NULL,
 timetable_detail_id BIGINT NOT NULL, substitution_date DATE NOT NULL, substitute_staff_id BIGINT NOT NULL,
 reason VARCHAR(255), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL, updated_at TIMESTAMP, updated_by BIGINT,
 CONSTRAINT uq_teacher_substitution UNIQUE (timetable_detail_id, substitution_date),
 CONSTRAINT fk_substitution_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
 CONSTRAINT fk_substitution_detail FOREIGN KEY (timetable_detail_id) REFERENCES class_timetable_details(timetable_detail_id),
 CONSTRAINT fk_substitution_staff FOREIGN KEY (substitute_staff_id) REFERENCES staff(staff_id)
);
CREATE INDEX idx_substitute_date ON teacher_substitutions (organization_id, substitute_staff_id, substitution_date, status);
