CREATE TABLE organization_calendar (
 calendar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id BIGINT NOT NULL,
 title VARCHAR(150) NOT NULL, description VARCHAR(1000), event_type VARCHAR(30) NOT NULL,
 start_date DATE NOT NULL, end_date DATE, is_holiday BOOLEAN NOT NULL DEFAULT FALSE,
 color_code VARCHAR(20), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL,
 updated_at TIMESTAMP, updated_by BIGINT,
 CONSTRAINT ck_calendar_dates CHECK (end_date IS NULL OR end_date >= start_date),
 CONSTRAINT fk_calendar_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id)
);
CREATE INDEX idx_calendar_dates ON organization_calendar (organization_id, start_date, end_date, status, is_holiday);

CREATE TABLE notices (
 notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id BIGINT NOT NULL,
 title VARCHAR(200) NOT NULL, description VARCHAR(3000) NOT NULL, notice_type VARCHAR(30) NOT NULL,
 publish_date DATE NOT NULL, expiry_date DATE, attachment_url VARCHAR(1000),
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_by BIGINT NOT NULL, updated_at TIMESTAMP, updated_by BIGINT,
 CONSTRAINT ck_notice_dates CHECK (expiry_date IS NULL OR expiry_date >= publish_date),
 CONSTRAINT fk_notice_org FOREIGN KEY (organization_id) REFERENCES organizations(organization_id)
);
CREATE INDEX idx_notice_publish ON notices (organization_id, status, publish_date, expiry_date);
