CREATE TABLE exam_types (
    exam_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    exam_type_name VARCHAR(100) NOT NULL,
    description VARCHAR(500), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL,
    updated_at TIMESTAMP, updated_by BIGINT,
    CONSTRAINT uq_exam_type UNIQUE (organization_id, exam_type_name)
);

CREATE TABLE exams (
    exam_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    academic_year_id BIGINT NOT NULL REFERENCES academic_years(academic_year_id),
    exam_type_id BIGINT NOT NULL REFERENCES exam_types(exam_type_id),
    exam_name VARCHAR(150) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', remarks VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL,
    updated_at TIMESTAMP, updated_by BIGINT,
    CONSTRAINT uq_exam_name UNIQUE (organization_id, academic_year_id, exam_name),
    CONSTRAINT ck_exam_dates CHECK (end_date >= start_date)
);

CREATE TABLE exam_targets (
    exam_target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    exam_id BIGINT NOT NULL REFERENCES exams(exam_id), class_id BIGINT NOT NULL REFERENCES classes(class_id),
    section_id BIGINT NOT NULL REFERENCES sections(section_id), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL,
    updated_at TIMESTAMP, updated_by BIGINT,
    CONSTRAINT uq_exam_target UNIQUE (exam_id, class_id, section_id)
);

CREATE TABLE exam_timetables (
    exam_timetable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    exam_target_id BIGINT NOT NULL REFERENCES exam_targets(exam_target_id),
    subject_id BIGINT NOT NULL REFERENCES subjects(subject_id), exam_date DATE NOT NULL,
    start_time TIME NOT NULL, end_time TIME NOT NULL, max_marks NUMERIC(8,2) NOT NULL,
    pass_marks NUMERIC(8,2) NOT NULL, room_number VARCHAR(50), status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT NOT NULL,
    updated_at TIMESTAMP, updated_by BIGINT,
    CONSTRAINT uq_exam_paper UNIQUE (exam_target_id, subject_id),
    CONSTRAINT ck_exam_time CHECK (end_time > start_time),
    CONSTRAINT ck_exam_marks CHECK (max_marks > 0 AND pass_marks >= 0 AND pass_marks <= max_marks)
);

CREATE TABLE student_marks (
    student_mark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    exam_timetable_id BIGINT NOT NULL REFERENCES exam_timetables(exam_timetable_id),
    student_id BIGINT NOT NULL REFERENCES students(student_id), obtained_marks NUMERIC(8,2),
    attendance_status VARCHAR(20) NOT NULL DEFAULT 'PRESENT', remarks VARCHAR(500),
    entered_by BIGINT NOT NULL, entered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP, CONSTRAINT uq_student_mark UNIQUE (exam_timetable_id, student_id),
    CONSTRAINT ck_obtained_marks CHECK (obtained_marks IS NULL OR obtained_marks >= 0)
);

CREATE TABLE mark_submissions (
    mark_submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    exam_timetable_id BIGINT NOT NULL UNIQUE REFERENCES exam_timetables(exam_timetable_id),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', submitted_by BIGINT,
    submitted_at TIMESTAMP, actioned_by_user_id BIGINT, actioned_by_staff_id BIGINT,
    actioned_by_role VARCHAR(50), actioned_at TIMESTAMP, reason VARCHAR(500)
);

CREATE INDEX idx_exams_year ON exams(organization_id, academic_year_id);
CREATE INDEX idx_exam_targets_exam ON exam_targets(organization_id, exam_id);
CREATE INDEX idx_exam_timetable_target ON exam_timetables(organization_id, exam_target_id);
CREATE INDEX idx_student_marks_paper ON student_marks(organization_id, exam_timetable_id);
