package com.wissenup.domain.fee.service;

import com.wissenup.domain.academic.repository.AcademicYearRepository;
import com.wissenup.domain.academic.repository.ClassRepository;
import com.wissenup.domain.academic.repository.SectionRepository;
import com.wissenup.domain.fee.dto.FeeRequests;
import com.wissenup.domain.fee.dto.FeeViews;
import com.wissenup.domain.fee.entity.FeePayment;
import com.wissenup.domain.fee.entity.FeeRefund;
import com.wissenup.domain.fee.entity.FeeStructure;
import com.wissenup.domain.fee.entity.FeeType;
import com.wissenup.domain.fee.entity.StudentFee;
import com.wissenup.domain.fee.repository.FeePaymentRepository;
import com.wissenup.domain.fee.repository.FeeRefundRepository;
import com.wissenup.domain.fee.repository.FeeStructureRepository;
import com.wissenup.domain.fee.repository.FeeTypeRepository;
import com.wissenup.domain.fee.repository.StudentFeeRepository;
import com.wissenup.domain.identity.repository.RoleRepository;
import com.wissenup.domain.student.entity.Student;
import com.wissenup.domain.student.entity.StudentEnrollment;
import com.wissenup.domain.student.repository.StudentEnrollmentRepository;
import com.wissenup.domain.student.repository.StudentParentRepository;
import com.wissenup.domain.student.repository.ParentRepository;
import com.wissenup.domain.student.repository.StudentRepository;
import com.wissenup.shared.exception.ConflictException;
import com.wissenup.shared.exception.ResourceNotFoundException;
import com.wissenup.shared.exception.ValidationException;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
@Service@RequiredArgsConstructor@Transactional public class FeeService{
 private final FeeTypeRepository types;private final FeeStructureRepository structures;private final StudentFeeRepository studentFees;private final FeePaymentRepository payments;private final FeeRefundRepository refunds;private final StudentRepository students;private final StudentEnrollmentRepository enrollments;private final StudentParentRepository studentParents;private final ParentRepository parents;private final AcademicYearRepository years;private final ClassRepository classes;private final SectionRepository sections;private final RoleRepository roles;
 @Transactional(readOnly=true)public List<FeeType>types(Long org){return types.findAllByOrganizationIdOrderByFeeName(org);}@Transactional(readOnly=true)public FeeType type(Long id,Long org){return types.findByFeeTypeIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Fee type",id));}@Transactional(readOnly=true)public List<FeeType>searchTypes(Long org,String name){return types.findAllByOrganizationIdAndFeeNameContainingIgnoreCaseOrderByFeeName(org,name);}
 public FeeType saveType(Long id,Long org,Long user,Long role,FeeRequests.Type r){requireAdmin(role);FeeType t=id==null?FeeType.builder().organizationId(org).createdBy(user).build():type(id,org);types.findByOrganizationIdAndFeeNameIgnoreCase(org,r.getFeeName().trim()).filter(x->!Objects.equals(x.getFeeTypeId(),id)).ifPresent(x->{throw new ConflictException("Fee type name already exists");});t.setFeeName(r.getFeeName().trim());t.setDescription(blank(r.getDescription()));t.setIsRecurring(Boolean.TRUE.equals(r.getIsRecurring()));t.setStatus(status(r.getStatus()));t.setUpdatedBy(user);return types.save(t);}public void archiveType(Long id,Long org,Long user,Long role){requireAdmin(role);FeeType t=type(id,org);t.setStatus("INACTIVE");t.setUpdatedBy(user);types.save(t);}
 @Transactional(readOnly=true)public List<FeeViews.Structure>structures(Long org,Long year,Long classId){List<FeeStructure>list=year==null?structures.findAllByOrganizationIdOrderByAcademicYearIdDescClassIdAsc(org):classId==null?structures.findAllByOrganizationIdAndAcademicYearIdOrderByClassIdAsc(org,year):structures.findAllByOrganizationIdAndAcademicYearIdAndClassIdAndStatusIgnoreCase(org,year,classId,"ACTIVE");return list.stream().map(this::structureView).toList();}
 @Transactional(readOnly=true)public FeeViews.Structure structure(Long id,Long org){return structureView(structureEntity(id,org));}
 public FeeViews.Structure saveStructure(Long id,Long org,Long user,Long role,FeeRequests.Structure r){requireAdmin(role);validatePlacement(org,r.getAcademicYearId(),r.getClassId());type(r.getFeeTypeId(),org);FeeStructure s=id==null?structures.findByOrganizationIdAndAcademicYearIdAndClassIdAndFeeTypeId(org,r.getAcademicYearId(),r.getClassId(),r.getFeeTypeId()).orElseGet(()->FeeStructure.builder().organizationId(org).createdBy(user).build()):structureEntity(id,org);s.setAcademicYearId(r.getAcademicYearId());s.setClassId(r.getClassId());s.setFeeTypeId(r.getFeeTypeId());s.setAmount(money(r.getAmount()));s.setDueDate(r.getDueDate());s.setDueDay(r.getDueDay());s.setFrequency(r.getFrequency()==null?"MONTHLY":r.getFrequency().toUpperCase());s.setStatus(status(r.getStatus()));s.setUpdatedBy(user);return structureView(structures.save(s));}public void archiveStructure(Long id,Long org,Long user,Long role){requireAdmin(role);FeeStructure s=structureEntity(id,org);s.setStatus("INACTIVE");s.setUpdatedBy(user);structures.save(s);}
 public List<FeeViews.StudentFee>assignStudent(Long org,Long user,Long role,FeeRequests.Assign r){requireAdmin(role);enrollments.findByOrganizationIdAndStudentIdAndAcademicYearIdAndClassIdAndStatusIgnoreCase(org,r.getStudentId(),r.getAcademicYearId(),r.getClassId(),"ACTIVE").orElseThrow(()->new ValidationException("Student is not actively enrolled in the selected class and academic year"));return assign(org,user,r.getStudentId(),r.getAcademicYearId(),r.getClassId()).stream().map(this::studentView).toList();}
 public FeeViews.AssignResult assignClass(Long org,Long user,Long role,FeeRequests.AssignClass r){requireAdmin(role);validatePlacement(org,r.getAcademicYearId(),r.getClassId());if(structures.findAllByOrganizationIdAndAcademicYearIdAndClassIdAndStatusIgnoreCase(org,r.getAcademicYearId(),r.getClassId(),"ACTIVE").isEmpty())throw new ValidationException("No active fee structure exists for the selected class and academic year");var list=enrollments.findAllByOrganizationIdAndAcademicYearIdAndClassIdAndStatusIgnoreCase(org,r.getAcademicYearId(),r.getClassId(),"ACTIVE");int count=0;for(var e:list)count+=assign(org,user,e.getStudentId(),r.getAcademicYearId(),r.getClassId()).size();return FeeViews.AssignResult.builder().studentsFound(list.size()).feesCreated(count).build();}
 private List<StudentFee>assign(Long org,Long user,Long student,Long year,Long classId){List<StudentFee>created=new ArrayList<>();for(FeeStructure s:structures.findAllByOrganizationIdAndAcademicYearIdAndClassIdAndStatusIgnoreCase(org,year,classId,"ACTIVE")){if(studentFees.findByOrganizationIdAndStudentIdAndFeeStructureId(org,student,s.getFeeStructureId()).isPresent())continue;created.add(studentFees.save(StudentFee.builder().organizationId(org).studentId(student).academicYearId(year).classId(classId).feeStructureId(s.getFeeStructureId()).feeTypeId(s.getFeeTypeId()).feeCategory("MANDATORY").totalAmount(s.getAmount()).balanceAmount(s.getAmount()).dueDate(s.getDueDate()).paymentStatus("PENDING").status("ACTIVE").createdBy(user).build()));}return created;}
 public FeeViews.StudentFee additional(Long org,Long user,Long role,FeeRequests.Additional r){requireAdmin(role);students.findByStudentIdAndOrganizationId(r.getStudentId(),org).orElseThrow(()->ResourceNotFoundException.notFound("Student",r.getStudentId()));type(r.getFeeTypeId(),org);StudentFee f=StudentFee.builder().organizationId(org).studentId(r.getStudentId()).academicYearId(r.getAcademicYearId()).feeTypeId(r.getFeeTypeId()).feeCategory("ADDITIONAL").totalAmount(money(r.getAmount())).balanceAmount(money(r.getAmount())).dueDate(r.getDueDate()).paymentStatus("PENDING").status("ACTIVE").createdBy(user).build();return studentView(studentFees.save(f));}
 public FeeViews.StudentFee discount(Long id,Long org,Long user,Long role,FeeRequests.Discount r){requireAdmin(role);StudentFee f=studentFees.lockByIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Student fee",id));BigDecimal discount=money(r.getDiscountAmount());BigDecimal max=f.getTotalAmount().subtract(f.getPaidAmount());if(discount.compareTo(max)>0)throw new ValidationException("Discount cannot exceed the unpaid fee amount");f.setDiscountAmount(discount);f.setDiscountReason(blank(r.getDiscountReason()));f.setUpdatedBy(user);recalculate(f);return studentView(studentFees.save(f));}
 @Transactional(readOnly=true)public List<FeeViews.StudentFee>studentFees(Long student,Long org){students.findByStudentIdAndOrganizationId(student,org).orElseThrow(()->ResourceNotFoundException.notFound("Student",student));return studentFees.findAllByOrganizationIdAndStudentIdOrderByDueDateAsc(org,student).stream().map(this::studentView).toList();}@Transactional(readOnly=true)public List<FeeViews.StudentFee>allStudentFees(Long org){return studentFees.findAllByOrganizationIdAndStatusIgnoreCaseOrderByDueDateAsc(org,"ACTIVE").stream().map(this::studentView).toList();}
 public FeeViews.Payment collect(Long org,Long user,Long role,FeeRequests.Payment r){requireFinance(role);StudentFee f=studentFees.lockByIdAndOrganizationId(r.getStudentFeeId(),org).orElseThrow(()->ResourceNotFoundException.notFound("Student fee",r.getStudentFeeId()));BigDecimal amount=money(r.getAmountPaid());if(amount.compareTo(f.getBalanceAmount())>0)throw new ValidationException("Payment cannot exceed the pending balance");String receipt=blank(r.getReceiptNumber());if(receipt==null)receipt="RCPT-"+org+"-"+LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+"-"+UUID.randomUUID().toString().substring(0,6).toUpperCase();if(payments.findByOrganizationIdAndReceiptNumber(org,receipt).isPresent())throw new ConflictException("Receipt number already exists");FeePayment p=payments.save(FeePayment.builder().organizationId(org).studentFeeId(f.getStudentFeeId()).studentId(f.getStudentId()).amountPaid(amount).paymentDate(r.getPaymentDate()).paymentMode(r.getPaymentMode().trim()).transactionReference(blank(r.getTransactionReference())).receiptNumber(receipt).remarks(blank(r.getRemarks())).createdBy(user).build());f.setPaidAmount(f.getPaidAmount().add(amount));recalculate(f);studentFees.save(f);return paymentView(p,f);}
 @Transactional(readOnly=true)public List<FeeViews.Payment>payments(Long org,Long student){List<FeePayment>list=student==null?payments.findAllByOrganizationIdOrderByPaymentDateDescCreatedAtDesc(org):payments.findAllByOrganizationIdAndStudentIdOrderByPaymentDateDescCreatedAtDesc(org,student);return list.stream().map(p->paymentView(p,studentFees.findById(p.getStudentFeeId()).orElse(null))).toList();}@Transactional(readOnly=true)public FeeViews.Payment payment(Long id,Long org){FeePayment p=payments.findByPaymentIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Payment",id));return paymentView(p,studentFees.findById(p.getStudentFeeId()).orElse(null));}@Transactional(readOnly=true)public FeeViews.Payment receipt(String no,Long org){FeePayment p=payments.findByOrganizationIdAndReceiptNumber(org,no).orElseThrow(()->new ResourceNotFoundException("Receipt not found"));return paymentView(p,studentFees.findById(p.getStudentFeeId()).orElse(null));}
 public FeeViews.Payment refund(Long org,Long user,Long role,FeeRequests.Refund r){requireFinance(role);FeePayment p=payments.lockByIdAndOrganizationId(r.getFeePaymentId(),org).orElseThrow(()->ResourceNotFoundException.notFound("Payment",r.getFeePaymentId()));BigDecimal amount=money(r.getRefundAmount()),available=p.getAmountPaid().subtract(p.getRefundedAmount());if(amount.compareTo(available)>0)throw new ValidationException("Refund cannot exceed the unrefunded payment amount");StudentFee f=studentFees.lockByIdAndOrganizationId(p.getStudentFeeId(),org).orElseThrow(()->ResourceNotFoundException.notFound("Student fee",p.getStudentFeeId()));refunds.save(FeeRefund.builder().organizationId(org).feePaymentId(p.getPaymentId()).refundAmount(amount).reason(blank(r.getReason())).refundedBy(user).build());p.setRefundedAmount(p.getRefundedAmount().add(amount));p.setPaymentStatus(p.getRefundedAmount().compareTo(p.getAmountPaid())==0?"REFUNDED":"PARTIALLY_REFUNDED");payments.save(p);f.setPaidAmount(f.getPaidAmount().subtract(amount));recalculate(f);studentFees.save(f);return paymentView(p,f);}
 private void recalculate(StudentFee f){BigDecimal payable=f.getTotalAmount().subtract(f.getDiscountAmount());f.setBalanceAmount(payable.subtract(f.getPaidAmount()).max(BigDecimal.ZERO));f.setPaymentStatus(f.getBalanceAmount().signum()==0?"PAID":f.getPaidAmount().signum()>0?"PARTIAL":"PENDING");}
 private FeeViews.Structure structureView(FeeStructure s){return FeeViews.Structure.builder().feeStructureId(s.getFeeStructureId()).organizationId(s.getOrganizationId()).academicYearId(s.getAcademicYearId()).classId(s.getClassId()).feeTypeId(s.getFeeTypeId()).academicYear(years.findById(s.getAcademicYearId()).map(v->v.getName()).orElse(null)).className(classes.findById(s.getClassId()).map(v->v.getName()).orElse(null)).feeTypeName(types.findById(s.getFeeTypeId()).map(FeeType::getFeeName).orElse(null)).amount(s.getAmount()).dueDate(s.getDueDate()).dueDay(s.getDueDay()).frequency(s.getFrequency()).status(s.getStatus()).build();}
 private FeeViews.StudentFee studentView(StudentFee f){Student s=students.findById(f.getStudentId()).orElse(null);StudentEnrollment e=enrollments.findFirstByStudentIdOrderByEnrollmentIdDesc(f.getStudentId()).orElse(null);return FeeViews.StudentFee.builder().studentFeeId(f.getStudentFeeId()).organizationId(f.getOrganizationId()).studentId(f.getStudentId()).academicYearId(f.getAcademicYearId()).classId(f.getClassId()).feeStructureId(f.getFeeStructureId()).feeTypeId(f.getFeeTypeId()).admissionNo(s==null?null:s.getAdmissionNo()).studentName(s==null?null:(s.getFirstName()+" "+Optional.ofNullable(s.getLastName()).orElse("")).trim()).parentName(parentName(f.getStudentId())).className(f.getClassId()==null?null:classes.findById(f.getClassId()).map(v->v.getName()).orElse(null)).sectionName(e==null?null:sections.findById(e.getSectionId()).map(v->v.getName()).orElse(null)).feeTypeName(types.findById(f.getFeeTypeId()).map(FeeType::getFeeName).orElse(null)).feeCategory(f.getFeeCategory()).totalAmount(f.getTotalAmount()).paidAmount(f.getPaidAmount()).discountAmount(f.getDiscountAmount()).balanceAmount(f.getBalanceAmount()).dueDate(f.getDueDate()).paymentStatus(f.getPaymentStatus()).status(f.getStatus()).discountReason(f.getDiscountReason()).build();}
 private FeeViews.Payment paymentView(FeePayment p,StudentFee f){FeeViews.StudentFee v=f==null?null:studentView(f);return FeeViews.Payment.builder().paymentId(p.getPaymentId()).organizationId(p.getOrganizationId()).studentFeeId(p.getStudentFeeId()).studentId(p.getStudentId()).academicYearId(f==null?null:f.getAcademicYearId()).admissionNo(v==null?null:v.getAdmissionNo()).studentName(v==null?null:v.getStudentName()).parentName(v==null?parentName(p.getStudentId()):v.getParentName()).className(v==null?null:v.getClassName()).sectionName(v==null?null:v.getSectionName()).feeTypeName(v==null?null:v.getFeeTypeName()).amountPaid(p.getAmountPaid()).refundedAmount(p.getRefundedAmount()).balanceAmount(f==null?null:f.getBalanceAmount()).totalAmount(f==null?null:f.getTotalAmount()).paymentDate(p.getPaymentDate()).paymentMode(p.getPaymentMode()).transactionReference(p.getTransactionReference()).receiptNumber(p.getReceiptNumber()).remarks(p.getRemarks()).paymentStatus(p.getPaymentStatus()).build();}
 private String parentName(Long studentId){return studentParents.findFirstByStudentIdOrderByIsPrimaryDesc(studentId).flatMap(link->parents.findById(link.getParentId())).map(parent->(parent.getFirstName()+" "+Optional.ofNullable(parent.getLastName()).orElse("")).trim()).orElse(null);}
 private void validatePlacement(Long org,Long year,Long classId){years.findById(year).filter(v->org.equals(v.getOrganizationId())).orElseThrow(()->ResourceNotFoundException.notFound("Academic year",year));classes.findById(classId).filter(v->org.equals(v.getOrganizationId())&&year.equals(v.getAcademicYearId())).orElseThrow(()->ResourceNotFoundException.notFound("Class",classId));}private FeeStructure structureEntity(Long id,Long org){return structures.findByFeeStructureIdAndOrganizationId(id,org).orElseThrow(()->ResourceNotFoundException.notFound("Fee structure",id));}
 private boolean hasRole(Long role,String...codes){String c=roles.findById(role).map(v->v.getCode()).orElse("");return Arrays.asList(codes).contains(c);}private void requireAdmin(Long role){if(!hasRole(role,"SCHOOL_ADMIN","ORG_ADMIN","SUPER_ADMIN"))throw new AccessDeniedException("Only a school administrator can configure fees");}private void requireFinance(Long role){if(!hasRole(role,"SCHOOL_ADMIN","ORG_ADMIN","SUPER_ADMIN","CASHIER"))throw new AccessDeniedException("Only an administrator or cashier can process payments");}private BigDecimal money(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP);}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}private String status(String s){return s==null||s.isBlank()?"ACTIVE":s.toUpperCase();}
}
